name: PR Checks
on:
  pull_request:
    branches: [ main, master, develop ]

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydb_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma client
      run: npx prisma generate

    - name: Run database migrations (test)
      run: npm run db:test:migrate
      env:
        DATABASE_URL: postgresql://myuser:mypassword@localhost:5432/mydb_test

    - name: Lint and type-check
      run: |
        npm run lint
        npm run type-check

    - name: Run unit tests (with coverage)
      run: npm run test:unit:coverage
      env:
        DATABASE_URL: postgresql://myuser:mypassword@localhost:5432/mydb_test

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run E2E tests
      run: npm run test:e2e
      env:
        DATABASE_URL: postgresql://myuser:mypassword@localhost:5432/mydb_test
